#                      11 june 

In [ ]:
## unoversal functions

In [4]:
## matrix product

import numpy as np
a=np.arange(0,9).reshape(3,3)

b=np.ones((3,3))
print(a)
print(b)
print(np.dot(a,b))          ## this is DOT product

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [5]:
np.sqrt([1,25,49,81])              # square root


array([1., 5., 7., 9.])

In [9]:
## gives the remainder
print(np.arange(7))
np.mod(np.arange(7),3)

[0 1 2 3 4 5 6]


array([0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [7]:
np.log(0)

C:\Users\MANISH\AppData\Local\Temp\ipykernel_5500\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [18]:
np.log(inf)

NameError: name 'inf' is not defined

In [22]:
np.log([1,2,3,4,5])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [26]:
## aggregate functions

a=np.array([1,2,3,4,5,6,7,8,9])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

45
1
9
5.0
2.581988897471611


In [34]:
## logical functions

np.all([[True,True],[True,True]])

True

In [10]:
np.all([[True,True],[True,False]])            ## if any of the value is fales then it gives false

False

In [46]:
np.array([[True,True],[True,False],[True,False]])

array([[ True,  True],
       [ True, False],
       [ True, False]])

In [42]:
np.all([-3,-2,0,1,5])       # 0 is always considered as false

False

In [37]:
np.all([-3,-2,1,5])  

True

In [22]:
np.any([1,0,2,0,5])      # if atleast one value is not zero the it's true

True

In [21]:
## all will check for all values
print(np.array([[True,True],[True,True],[True,False]]))
np.all(np.array([[True,True],[True,True],[True,False]]),axis=0)       # axis = 0 means column checking columns are true or false

[[ True  True]
 [ True  True]
 [ True False]]


array([ True, False])

In [23]:
print(np.array([[True,True],[True,True],[True,False]]))
np.all(np.array([[True,True],[True,True],[True,False]]),axis=1)        ## axis=1 means rows checking rows are true or false

[[ True  True]
 [ True  True]
 [ True False]]


array([ True,  True, False])

In [24]:
## any will check for  atleast one true values
print(np.array([[True,True],[True,True],[True,False]]))

np.any(np.array([[True,True],[True,True],[True,False]]),axis=0)          

[[ True  True]
 [ True  True]
 [ True False]]


array([ True,  True])

In [25]:

print(np.array([[True,True],[False,True],[False,False]]))
np.any(np.array([[True,True],[False,True],[False,False]]),axis=1)          # if any value is false then it will print false 

[[ True  True]
 [False  True]
 [False False]]


array([ True,  True, False])

In [56]:
## logic functions

In [64]:
x=np.array([0,1,2,3,4])
print(np.logical_and(x>1,x<4))        # if both the true only then true
print(np.logical_or(x>1,x<4))         # atlest one condition should be true
print(np.logical_not(x>1,x<4))        ## revers the outcome

[False False  True  True False]
[ True  True  True  True  True]
[ True  True False False False]


In [ ]:
########                              indexing  

In [77]:
import numpy as np
arr=np.arange(21,26)
print(arr)
print(arr[0])                          ## i d indexing
print(arr[-5])
print(arr[1:3])
print(arr[-4:-2])

[21 22 23 24 25]
21
21
[22 23]
[22 23]


In [ ]:
  ###      multiple dimention indexing
    
    


In [10]:
import numpy as np
arr=np.arange(21,30).reshape(3,3)
print(arr)

print(arr[0,0])
print(arr[2,0])
print(arr[0,1])
print(arr[1,2])

print(arr[0,0],arr[2,0],arr[0,1],arr[1,2])


[[21 22 23]
 [24 25 26]
 [27 28 29]]
21
27
22
26
21 27 22 26


In [26]:
import numpy as np
arr=np.arange(21,30).reshape(3,3)
print(arr)
print('-----------')
print(arr[0:2,0:2])
print(arr[1:3,1:2])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
-----------
[[21 22]
 [24 25]]
[[25]
 [28]]


In [34]:
print(arr[0:2,1:3])

[[22 23]
 [25 26]]


In [35]:
### array transformation

# reshape and resize are allready explained
import numpy as np
arr=np.arange(21,30).reshape(3,3)                         
print(arr)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [38]:
arr.ravel()          ##### ravel -removes dimention, convert the 2d array in 1d array    ## original array will not be change

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
arr.transpose()             ## it will convetr array transpose    ## original array will not be change

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [41]:
#concatenate

a=np.arange(21,30).reshape(3,3)                         
print(a)
b=np.arange(51,60).reshape(3,3)
print(b)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
[[51 52 53]
 [54 55 56]
 [57 58 59]]


In [46]:
np.concatenate((a,b))          ## defalut

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [47]:
np.concatenate((a,b),axis=0)      #row wise

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [49]:
np.concatenate((a,b),axis=1)# column wise

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [50]:
np.stack((a,b))

array([[[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [51]:
np.column_stack((a,b))

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [53]:
np.hstack((a,b))            ## horizontal stacking

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [55]:
np.vstack((a,b))         # vertical stacking

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [ ]:
## split

In [59]:
x=np.arange(9)
print(x)
print(np.split(x,3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [62]:
a=np.arange(16).reshape(4,4)                  ## split it horizontaly
print(a)
np.hsplit(a,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
np.vsplit(a,2)                   ## split it in verticaly

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]