#                                        5 june

In [2]:
##  numpy
!pip install numpy

In [3]:
import numpy as np

In [5]:
len(dir(np))

608

In [6]:
## creat a 'N-Dimentional array'

import numpy as np

a=[1,2,3,4,5,6,7]
na = np.array(a)
print(na)
type(na)

[1 2 3 4 5 6 7]


numpy.ndarray

In [7]:
a=(1,2,3,4,5,6,7)
na = np.array(a)            # numpy array output is in list always
print(na)
type(na)

[1 2 3 4 5 6 7]


numpy.ndarray

In [7]:
## attributes of ndarray
a=(1,2,3,4,5,6,7)
n = np.array(a)
print(n)
print(type(n))
print('------attributes-----')
print(n.shape)                  #gives no of (rows,column)
print(n.size)                   #no of elements
print(n.ndim)                   # gives dimensions
print(n.dtype)                  #deta type int ,float
print(n.itemsize)               # for storing 10 how many bytes are using

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
------attributes-----
(7,)
7
1
int32
4


In [17]:
st=[1,10.5,52,'manish']
p=np.array(st)
print(p)
print('------attributes-----')
print(p.shape)                  
print(p.size)                  
print(p.ndim)                           ### 1 d array
print(p.dtype)                  
print(p.itemsize)               

['1' '10.5' '52' 'manish']
------attributes-----
(4,)
4
1
<U32
128


In [24]:
st=[[1,2,3],[5,4,8],[5,6,5]]
p=np.array(st)
print(p)
print('------attributes-----')
print(p.shape)                  
print(p.size)                  
print(p.ndim)                           ##2d array       
print(p.dtype)                  
print(p.itemsize)   

[[1 2 3]
 [5 4 8]
 [5 6 5]]
------attributes-----
(3, 3)
9
2
int32
4


In [26]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
np.linspace(0,20,3)             #bet 0,20    3- means 3 nos of equal space 

array([ 0., 10., 20.])

In [39]:

## copy


a=np.array([1,2,3,4,5])
print(id(a))
b=np.array([1,2,3,4,5])
print(id(b))
c=a                                                                 ### take a look again
d=a.copy()
print(id(c))
print(id(d))
print(a)
print(b)
print(c)
print(d)

1964372519696
1964372518448
1964372519696
1964372520368
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [40]:
### arithmatic operation
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)



[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [53]:
## reshape and resize

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(4,3))                   # change shape but original will be remails same
print(a)

print(a.resize(4,3))                  # it will change the original shape
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
None
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [11]:
## 2 d array multiplication

a=np.array([5,7,8,6,13,4,8,15,32])
b=np.array([1,2,3,4,5,6,7,8,9])
a.resize(3,3)
print(a)
b.resize(3,3)
print(b)
print(a*b)

[[ 5  7  8]
 [ 6 13  4]
 [ 8 15 32]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  5  14  24]
 [ 24  65  24]
 [ 56 120 288]]
